#pragma once
#include "types.h"
#include <string>
#include <vector>

/*
	DAVID'S CHARACTER-SELECT UTILITY, ported - `0915/flycast-rr/mcp/charselect.py`
	(2026-09-12, "verified against the emulator"). The MvC2 select globe as a vertical
	torus of rows [8,8,8,6,6,6,6,8] (David's GRID, anchored at RubyHeart's row): vertical
	moves are straight in cols 0-5 and FOLD col6->4 / col7->5 crossing an 8-wide row into
	a 6-wide one (UN-FOLD col4->6 / col5->7 the other way); horizontal wraps per-row width.
	Cursor moves are PRESS-EDGE: a held direction moves once, the same direction twice
	needs a neutral between. The cursor RESETS to the player's home after each lock.

	`[MEASURED 2026-09-18]` on this build, from power-on: fastVS_mcp + build_picks for
	P1 Dhalsim/Cable/Sentinel, P2 Ryu/Ken/Guile -> ID_2 slots 37/23/52 and 0/39/2, first
	try, on David's timing table. THIS is how the Dhalsim base is authored (css_tour.cpp).

	The pure part only: no emulator, no ImGui. Parity with the Python is a CSS SELFTEST
	claim against scripts/fixtures/mvc2/css/dhalsim_team_picks.txt (generated BY the
	Python; seqHashMacro 3b736c94ef884bbd, 378 frames).
*/
namespace roll {
namespace css {

//! One press of a direction code ("U","D","L","R","UL","UR","DL","DR"), David's DELTA8.
struct Pick { std::string name; std::string palette; char assist; };	//!< ("Dhalsim","LP",'A')

struct Timing
{
	int navgap = 1;		//!< neutral frames between cursor presses (>=1 so a repeated dir re-presses)
	int preselect = 8;	//!< settle after the last nav move before the SELECT (palette) press
	int postsel = 24;	//!< wait after SELECT before the assist move / CONFIRM
	int astgap = 12;	//!< neutral between assist DOWN presses
	int preconf = 12;	//!< wait after the last assist move before CONFIRM
	int postconf = 72;	//!< wait after CONFIRM before the next slot's nav (the ~60f lockout)
};

// ---- the grid ----------------------------------------------------------------------
bool        known(const std::string& name);					//!< a canonical GRID name
int         idOf(const std::string& name);					//!< ID_2 value (David's NAMES), -1 unknown
const char *nameOf(int id);									//!< "" unknown
std::string neighbor(const std::string& name, const char *dir);	//!< one press away; "" if unknown
std::vector<std::string> plan(const std::string& target, const std::string& start = "RubyHeart");	//!< dir codes U/D/L/R
std::string home(int player);								//!< 0 -> "RubyHeart", 1 -> "Cable"

// ---- streams ------------------------------------------------------------------------
//! Canon bits (tasmacro.h CANON_*) for one press of `dir` by `player` (0/1).
u16  dirCanon(int player, const char *dir);
u16  paletteCanon(int player, const std::string& palette);	//!< LP/HP/A1/LK/HK/A2 -> the button bit
//! David's build_picks: one player's per-frame canon stream for up to 3 picks (0 = neutral frame).
std::vector<u16> buildPicks(int player, const std::vector<Pick>& picks, const Timing& t = Timing());
//! David's merge_players + the CE letter rendering, one line per frame ('.' neutral).
std::vector<std::string> renderLetters(const std::vector<u16>& p1, const std::vector<u16>& p2);
bool parsePick(const std::string& s, Pick& out, std::string& err);	//!< "dhalsim-lp-a"

// ---- the oracle's addresses (Demul 0x2C.., David's tables; flycast = +0x60000000) -----
enum class Slot : u8 { P1_A, P1_B, P1_C, P2_A, P2_B, P2_C };
u32 id2Addr(Slot s);		//!< ID_2 (the live cursor / the locked character)
u32 assistAddr(Slot s);		//!< Assist_Value 0 alpha / 1 beta / 2 gamma
u32 paletteAddr(Slot s);	//!< PaletteID_2 (0 LP 1 LK 2 HP 3 HK 4 A1 5 A2)

void selfTest();

}	// namespace css
}	// namespace roll
